name: glutino_app
description: "Application de d√©tection de gluten"
publish_to: 'none'
environment:
  sdk: '^3.0.0'

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.0.0
  iconsax: ^0.0.8 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

