name: glutino_app
description: "Application de d√©tection de gluten"
publish_to: 'none'
environment:
  sdk: '^3.0.0'

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.0.0
  iconsax: ^0.0.8 
  shared_preferences: ^2.5.4
  provider: ^6.1.5+1
  google_sign_in: ^6.1.6
  mobile_scanner: ^6.0.4
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/recipes/