name: glutino_app
description: "Application de d√©tection de gluten"
publish_to: 'none'
environment:
  sdk: '^3.0.0'

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.0.0
  iconsax: ^0.0.8 
  shared_preferences: ^2.5.4
  provider: ^6.1.5+1
  google_sign_in: ^6.1.6
  mobile_scanner: ^6.0.4
  http: ^1.2.0
  share_plus: ^10.0.0
  maps_launcher: ^3.0.0
  url_launcher: ^6.3.0
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  flutter_facebook_auth: ^7.0.0
  sign_in_with_apple: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/recipes/